# Workflow simple pour déployer du contenu statique sur les pages GitHub
name: Deploiement de la page

on:
  # S'exécute sur des push ciblant la branche par défaut
  push:
    branches: ["main"]

  # Vous permet d'exécuter ce workflow manuellement à partir de l'onglet Actions
  workflow_dispatch:

# Définit les autorisations de GITHUB_TOKEN pour permettre le déploiement sur les pages GitHub
permissions:
  contents: read
  pages: write
  id-token: write

# Autoriser un seul déploiement simultané, en ignorant les exécutions mises en file d'attente entre l'exécution en cours et la dernière mise en file d'attente.
# Cependant, n'annulez PAS les exécutions en cours, car nous souhaitons permettre à ces déploiements de production de se terminer.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Travail de déploiement unique puisque nous sommes juste en train de déployer
  deploy:
    environment:
      name: Ma github page
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Télécharger l'intégralité du référentiel
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
